# Generated by Django 5.0.1 on 2024-03-05 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctrl_comb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(db_comment='Descripcion del modelo de Vehiculo', max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ctrl_comb.brand')),
            ],
            options={
                'verbose_name': 'Modelos',
                'verbose_name_plural': 'Modelos',
                'db_table': 'model',
                'db_table_comment': 'Modelos de Vehiculos',
            },
        ),
    ]
