# Generated by Django 5.0.1 on 2024-03-13 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctrl_comb', '0002_models'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Models',
            new_name='Modelo',
        ),
    ]
